#
#    |    |  |  /\   |\/|
#   |___ \__/ /~~\  |  |
#
#   The Luam project gradle.properties
#   Licensed under the GNU GPLv3

# Core
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Daemons
org.gradle.daemon=true

# Compiler
org.gradle.jvmargs=-Xms256M -Xmx1G -XX:+UseG1GC

# Java Toolchains
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.fromEnv=JAVA_HOME,JAVA_25_HOME,JDK25,JDK25_HOME,JDK_25_HOME,JAVA25,JAVA25_HOME

# Console
org.gradle.console=colored
org.gradle.warning.mode=summary

# Kotlin
kotlin.code.style=official
kotlin.allwarningsaserrors=true
kotlin.incremental=true

# Luam
luam.version=1.0.0
